go2rtc:
  url: "http://127.0.0.1:1984"

homeassistant:
  allowlist_external_dirs:
    - "/media"

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest:
  - resource: http://localhost:61210/api/4/sensors
    scan_interval: 60
    sensor:
      - name: "HA Laptop Battery"
        value_template: >
          {{ value_json
             | selectattr('type', 'equalto', 'battery')
             | map(attribute='value')
             | first }}
        unit_of_measurement: "%"

      - name: "HA Laptop Battery Status"
        value_template: >
          {{ value_json
             | selectattr('type', 'equalto', 'battery')
             | map(attribute='status')
             | first }}
