- id: '1768151254676'
  name: Anocheciendo
  entities:
    light.luces_testigo:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 128
      color_temp_kelvin: 3234
      color_temp: 309
      hs_color:
      - 27.48
      - 50.885
      rgb_color:
      - 255
      - 185
      - 125
      xy_color:
      - 0.475
      - 0.38
      entity_id:
      - light.edison_smoke_cct_wifi_bluetooth
      - light.tecla_entrada_cocina_switch_1
      - light.luz_testigo
      - light.tecla_cocina_switch_2
      icon: mdi:lightbulb-group
      friendly_name: Luces Testigo
      supported_features: 0
      state: 'on'
    light.luces_frente:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Luces Frente
      supported_features: 0
      state: 'on'
  icon: mdi:weather-sunset-down
  metadata:
    light.luces_testigo:
      entity_only: true
    light.luces_frente:
      entity_only: true
- id: '1768504829483'
  name: Hora de dormir
  entities:
    light.todas_las_luces_interior:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      entity_id:
      - light.device595cdf
      - light.edison_smoke_cct_wifi_bluetooth
      - light.tecla_pasillo_switch_2
      - light.luz_ducha
      - light.luz_estudio
      - light.luz_oficina
      - light.tecla_ambiente_switch_2
      - light.tecla_ambiente_switch_3
      - light.tecla_cocina_switch_1
      - light.tecla_entrada_living_switch_1
      - light.tecla_entrada_living_switch_3
      - light.wifi_smart_switch
      - light.luz_testigo
      icon: mdi:lightbulb-group
      friendly_name: Todas las luces interior
      supported_features: 0
      state: 'off'
  icon: mdi:sleep
  metadata:
    light.todas_las_luces_interior:
      entity_only: true
- id: '1768504896843'
  name: Amaneciendo
  entities:
    light.luces_frente:
      supported_color_modes:
      - onoff
      color_mode:
      friendly_name: Luces Frente
      supported_features: 0
      state: 'off'
  icon: mdi:white-balance-sunny
  metadata:
    light.luces_frente:
      entity_only: true
